#!/bin/sh

. /opt/etc/keenetic-pbr/defaults

log()
{
  logger -t "keenetic-pbr" "$1"
  echo "[keenetic-pbr] $1"
}

enable_hwnat()
{
  log "Enabling HW NAT..."
  sysctl -w net.ipv4.netfilter.ip_conntrack_fastnat=1 2>/dev/null || true # NDMS2
  sysctl -w net.netfilter.nf_conntrack_fastnat=1 2>/dev/null || true # NDMS3
}

disable_hwnat()
{
  log "Disabling HW NAT..."
  sysctl -w net.ipv4.netfilter.ip_conntrack_fastnat=0 2>/dev/null || true # NDMS2
  sysctl -w net.netfilter.nf_conntrack_fastnat=0 2>/dev/null || true # NDMS3
}

apply_lists_and_routing()
{
  log "Applying lists and routing configuration..."
  $KEENETIC_PBR -config "$CONFIG" apply
}

apply_routing()
{
  log "Applying routing configuration..."
  $KEENETIC_PBR -config "$CONFIG" apply --skip-dnsmasq --skip-ipset
}

unapply_routing()
{
  log "Removing routing configuration..."
  $KEENETIC_PBR -config "$CONFIG" undo-routing
}

restart_dnsmasq()
{
  log "Restarting dnsmasq..."
  /opt/etc/init.d/S56dnsmasq restart
  log "dnsmasq restarted"
}

start()
{
  disable_hwnat
  apply_lists_and_routing
  restart_dnsmasq
}

stop()
{
  enable_hwnat
  unapply_routing
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    sleep 2
    start
    ;;
  download-lists|download_lists)
    log "Downloading lists..."
    $KEENETIC_PBR -config "$CONFIG" download
    log "Lists downloaded. Please run '/opt/etc/init.d/S80keenetic-pbr apply-lists' to make use of them or restart OPKG."
    ;;
  apply-lists|apply_lists)
    apply_lists_and_routing
    ;;
  apply-routing|apply_routing)
    apply_routing
    ;;
  self-check)
    $KEENETIC_PBR -config "$CONFIG" self-check
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|download-lists|apply-lists|apply-routing|self-check}"
    ;;
esac