#!/bin/sh

. /opt/etc/keenetic-pbr/defaults

log()
{
  logger -t "keenetic-pbr" "$1"
  echo "${ansi_blue}[keenetic-pbr]${ansi_white} $1${ansi_std}" >&2
}

enable_hwnat()
{
  log "Enabling HW NAT..."
  sysctl -w net.ipv4.netfilter.ip_conntrack_fastnat=1 2>/dev/null || true # NDMS2
  sysctl -w net.netfilter.nf_conntrack_fastnat=1 2>/dev/null || true # NDMS3
}

disable_hwnat()
{
  log "Disabling HW NAT..."
  sysctl -w net.ipv4.netfilter.ip_conntrack_fastnat=0 2>/dev/null || true # NDMS2
  sysctl -w net.netfilter.nf_conntrack_fastnat=0 2>/dev/null || true # NDMS3
}

apply_lists_and_routing()
{
  log "Applying routing configuration and importing IPs/CIDRs to ipsets..."
  $KEENETIC_PBR -config "$CONFIG" apply
}

apply_routing()
{
  log "Applying routing configuration..."
  $KEENETIC_PBR -config "$CONFIG" apply -skip-ipset
}

unapply_routing()
{
  log "Removing routing configuration..."
  $KEENETIC_PBR -config "$CONFIG" undo-routing
}

check() {
  # Checking dnsmasq
  /opt/etc/init.d/S56dnsmasq check

  # Checking keenetic-pbr state
  echo "Checking keenetic-pbr state"
  $KEENETIC_PBR -config "$CONFIG" self-check

  echo "Currently configured ipset lists:"
  ipset list -t
}

generate_dnsmasq_config()
{
  $KEENETIC_PBR -config "$CONFIG" print-dnsmasq-config
}

start()
{
  disable_hwnat
  apply_lists_and_routing
}

stop()
{
  enable_hwnat
  unapply_routing
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    sleep 2
    start
    ;;
  download-lists|download_lists|update)
    log "Downloading lists..."
    $KEENETIC_PBR -config "$CONFIG" download
    log "Lists downloaded. Please run '/opt/etc/init.d/S80keenetic-pbr restart' to make use of them or restart OPKG."
    ;;
  apply-lists|apply_lists)
    apply_lists_and_routing
    ;;
  apply-routing|apply_routing)
    apply_routing
    ;;
  generate-dnsmasq-config)
    generate_dnsmasq_config
    ;;
  check|status|self-check|self_check)
    check
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|check|status|download-lists|apply-lists|apply-routing}"
    ;;
esac