/* eslint-disable */
/**
 * This file was automatically generated by guts.
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * To regenerate this file, run:
 *   make generate-types
 */

// Code generated by 'guts'. DO NOT EDIT.

// From api/errors.go
/**
 * APIError represents a structured API error response.
 */
export interface APIError {
    code: ErrorCode;
    message: string;
    // empty interface{} type, falling back to unknown
    details?: Record<string, unknown> | null;
}

// From config/types.go
export interface AutoUpdateConfig {
    /**
     * Enabled enables automatic background updates of lists with URLs (default: true).
     */
    enabled: boolean;
    /**
     * IntervalHours is the interval in hours for automatic list updates (default: 24 hours, min: 1 hour).
     */
    interval_hours: number;
}

// From api/types.go
/**
 * CheckRequest contains the host (domain or IP) to check.
 */
export interface CheckRequest {
    host: string;
}

// From api/types.go
/**
 * CheckResult contains the result of a single health check.
 */
export interface CheckResult {
    passed: boolean;
    message?: string;
}

// From config/types.go
export interface Config {
    /**
     * ConfigVersion is the configuration file version.
     */
    config_version: number;
    /**
     * General holds general configuration.
     */
    General: GeneralConfig | null;
    /**
     * IPSets is the ipset configuration. You can add multiple ipsets.
     */
    IPSets: (IPSetConfig | null)[];
    /**
     * Lists contains lists with domains/IPs/CIDRs. You can add multiple lists and use them in ipsets by providing their name. You must set "name" and either "url", "file" or "hosts" field for each list.
     */
    Lists: (ListSource | null)[];
}

// From config/hasher.go
/**
 * ConfigHashData represents the structure used for hashing
 */
export interface ConfigHashData {
    general: GeneralConfig | null;
    ipsets: (IPSetHashData | null)[];
    list_md5s: Record<string, string> | null;
    dns_servers: string[]; // Resolved DNS server strings
}

// From config/types.go
export interface DNSServerConfig {
    /**
     * Enable enables transparent DNS proxy for domain-based routing (default: true).
     */
    enable: boolean;
    /**
     * ListenAddr is the DNS proxy listen address (default: [::] for dual-stack IPv4/IPv6, or a specific IP like 127.0.0.1).
     */
    listen_addr: string;
    /**
     * ListenPort is the port for DNS proxy listener (default: 15353).
     */
    listen_port: number;
    /**
     * Upstreams lists upstream DNS servers. Supported: keenetic://, udp://ip:port, doh://host/path (default: ["keenetic://"]).
     */
    upstreams: string[];
    /**
     * CacheMaxDomains is the maximum number of domains to cache in DNS proxy (default: 1000).
     */
    cache_max_domains: number;
    /**
     * DropAAAA drops AAAA (IPv6) DNS responses (default: true).
     */
    drop_aaaa: boolean;
    /**
     * IPSetEntryAdditionalTTLSec is added to DNS record TTL to determine IPSet entry lifetime in seconds (default: 7200 = 2 hours).
     */
    ipset_entry_additional_ttl_sec: number;
    /**
     * ListedDomainsDNSCacheTTLSec is the TTL used for DNS cache entries of domains matched by lists (default: 30). Allows clients to forget DNS fast for listed domains. Other domains keep original TTL.
     */
    listed_domains_dns_cache_ttl_sec: number;
    /**
     * Remap53Interfaces are interfaces to intercept DNS traffic on (default: ["br0", "br1"]).
     */
    remap_53_interfaces: string[];
}

// From service/dns_service.go
/**
 * DNSServerInfo represents a DNS server with formatted output support.
 */
export interface DNSServerInfo {
    type: string;
    endpoint: string;
    domain?: string | null;
    proxy: string;
    port?: string;
}

// From api/dns.go
/**
 * DNSServersResponse represents the response for the DNS servers endpoint.
 * Uses DNSServerInfo from types.go (which uses the shared service type).
 */
export interface DNSServersResponse {
    servers: DNSServerInfo[];
}

// From api/types.go
/**
 * DataResponse wraps successful responses with a "data" field.
 */
export interface DataResponse {
    // empty interface{} type, falling back to unknown
    data: unknown;
}

// From api/errors.go
export enum ErrorCode {
    ErrCodeConflict = "conflict",
    ErrCodeForbidden = "forbidden",
    ErrCodeInternalError = "internal_error",
    ErrCodeInvalidRequest = "invalid_request",
    ErrCodeNotFound = "not_found",
    ErrCodeServiceError = "service_error",
    ErrCodeValidationFailed = "validation_failed"
}

// From api/errors.go
/**
 * ErrorResponse wraps an APIError for JSON responses.
 */
export interface ErrorResponse {
    error: APIError;
}

// From config/types.go
export interface GeneralConfig {
    /**
     * ListsOutputDir is the directory for downloaded lists.
     */
    lists_output_dir: string;
    /**
     * InterfaceMonitoringIntervalSeconds is the interval in seconds for interface monitoring (0 = disabled, default: 0).
     */
    interface_monitoring_interval_seconds: number;
    /**
     * AutoUpdate lists settings
     */
    auto_update_lists: AutoUpdateConfig | null;
    /**
     * DNS Server settings
     */
    dns_server: DNSServerConfig | null;
}

// From api/types.go
/**
 * HealthCheckRequest contains parameters for health checks.
 */
export interface HealthCheckRequest {
    ipset_name?: string;
    domain?: string;
}

// From api/types.go
/**
 * HealthCheckResponse returns health check results.
 */
export interface HealthCheckResponse {
    healthy: boolean;
    checks: Record<string, CheckResult> | null;
}

// From api/types.go
/**
 * HostnameRuleMatch represents a rule that matched by hostname pattern.
 */
export interface HostnameRuleMatch {
    rule_name: string;
    pattern: string;
}

// From config/config.go
export enum IPFamily {
    Ipv4 = 4,
    Ipv6 = 6
}

// From api/types.go
/**
 * IPSetCheckResult contains check results for one IP address.
 */
export interface IPSetCheckResult {
    ip: string;
    rule_results: RuleCheckResult[];
}

// From config/types.go
export interface IPSetConfig {
    /**
     * IPSetName is the name of the ipset.
     */
    ipset_name: string;
    /**
     * Lists adds all hosts from the following lists to this ipset.
     */
    lists: string[];
    /**
     * IPVersion is the IP version (4 or 6).
     */
    ip_version: IPFamily;
    /**
     * FlushBeforeApplying clears ipset each time before filling it.
     */
    flush_before_applying: boolean;
    routing?: RoutingConfig | null;
    /**
     * IPTablesRules are iptables rules for this ipset (you can provide multiple rules). Available variables: {{ipset_name}}, {{fwmark}}, {{table}}, {{priority}}.
     */
    iptables_rule?: (IPTablesRule | null)[];
}

// From config/hasher.go
/**
 * IPSetHashData represents hashable IPSet configuration
 */
export interface IPSetHashData {
    ipset_name: string;
    lists: string[];
    ip_version: IPFamily;
    flush_before_applying: boolean;
    routing: RoutingConfig | null;
    iptables_rules: (IPTablesRule | null)[];
}

// From api/types.go
/**
 * IPSetsResponse returns all ipsets in the configuration.
 */
export interface IPSetsResponse {
    ipsets: (IPSetConfig | null)[];
}

// From config/types.go
export interface IPTablesRule {
    chain: string;
    table: string;
    rule: string[];
}

// From config/config.go
export const IPTablesTmplFwmark = "fwmark";

// From config/config.go
export const IPTablesTmplIpset = "ipset_name";

// From config/config.go
export const IPTablesTmplPriority = "priority";

// From config/config.go
export const IPTablesTmplTable = "table";

// From service/interface_service.go
/**
 * InterfaceInfo represents a network interface with optional Keenetic metadata.
 */
export interface InterfaceInfo {
    index: number;
    name: string;
    is_up: boolean;
    is_loopback: boolean;
    ip_addresses?: string[];
    /**
     * Keenetic-specific fields (nil if Keenetic API not available)
     */
    keenetic_id?: string;
    keenetic_description?: string;
    keenetic_link?: string;
    keenetic_connected?: string;
}

// From api/interfaces.go
/**
 * InterfacesResponse represents the response for the interfaces list endpoint.
 */
export interface InterfacesResponse {
    interfaces: InterfaceInfo[];
}

// From api/types.go
/**
 * ListDownloadResponse returns the result of downloading a list.
 */
export interface ListDownloadResponse extends ListInfo {
    changed: boolean; // true if the list was updated, false if unchanged
}

// From api/types.go
/**
 * ListInfo contains list information with statistics.
 */
export interface ListInfo {
    list_name: string;
    type: string; // "url", "file", "hosts"
    url?: string;
    file?: string;
    hosts?: string[]; // Only included for GET single list of type "hosts"
    stats: ListStatistics | null; // nil if statistics not yet calculated
}

// From config/types.go
export interface ListSource {
    /**
     * ListName is the name of the list.
     */
    list_name: string;
    /**
     * URL is the URL of the list (optional).
     */
    url?: string;
    /**
     * File is the local file path of the list (optional).
     */
    file?: string;
    /**
     * Hosts is a list of host entries for the list (optional).
     */
    hosts?: string[];
}

// From api/types.go
/**
 * ListStatistics contains statistics about list content and download status.
 * Count fields (TotalHosts, IPv4Subnets, IPv6Subnets) are pointers and will be
 * null in JSON if statistics haven't been calculated yet.
 * Download status (Downloaded, LastModified) is always available for URL-based lists.
 */
export interface ListStatistics {
    total_hosts: number | null; // null if not yet calculated
    ipv4_subnets: number | null; // null if not yet calculated
    ipv6_subnets: number | null; // null if not yet calculated
    downloaded?: boolean; // Only for URL-based lists
    last_modified?: string | null; // RFC3339 format, only for URL-based lists
}

// From api/types.go
/**
 * ListsResponse returns all lists in the configuration.
 */
export interface ListsResponse {
    lists: (ListInfo | null)[];
}

// From api/types.go
/**
 * PingCheckResponse returns ping results for a host.
 */
export interface PingCheckResponse {
    host: string;
    resolved_ip?: string;
    success: boolean;
    packets_sent?: number;
    packets_received?: number;
    packet_loss?: number;
    min_rtt?: number; // milliseconds
    avg_rtt?: number; // milliseconds
    max_rtt?: number; // milliseconds
    output?: string;
    error?: string;
}

// From api/types.go
/**
 * RoutingCheckResponse returns detailed routing information for a host.
 */
export interface RoutingCheckResponse {
    host: string;
    resolved_ips?: string[];
    matched_by_hostname?: HostnameRuleMatch[];
    ipset_checks: IPSetCheckResult[];
}

// From config/types.go
export interface RoutingConfig {
    /**
     * Interfaces is the list of interfaces to direct traffic for IPs in this ipset. keen-pbr will use the first available interface. Keenetic API will be queried automatically to check network connectivity on interfaces. If all interfaces are down, traffic will be blocked (blackhole route) or allowed to leak based on kill_switch setting.
     */
    interfaces: string[];
    /**
     * DefaultGateway is the default gateway IP address to use instead of interface-based routing. Must match the IP version of the ipset (IPv4 for ipv4, IPv6 for ipv6). If set, this gateway will be used when no interface is available or no interfaces are configured.
     */
    default_gateway?: string;
    /**
     * KillSwitch defines kill switch behavior when all interfaces are down. If true (default): traffic is blocked via blackhole route (no leaks). If false: ip rules and iptables rules are removed, allowing traffic to use default routing (leaks allowed).
     */
    kill_switch: boolean;
    /**
     * FwMark is the fwmark to apply to packets matching the list criteria.
     */
    fwmark: number;
    /**
     * IPRouteTable is the iptables routing table number.
     */
    table: number;
    /**
     * IPRulePriority is the iptables routing rule priority.
     */
    priority: number;
    /**
     * DNS settings for this routing rule
     */
    dns?: RoutingDNSConfig | null;
}

// From config/types.go
export interface RoutingDNSConfig {
    /**
     * Upstreams overrides DNS server for domains in this ipset. Format: <server>[#port] (e.g., 1.1.1.1#53 or 8.8.8.8).
     */
    upstreams: string[];
}

// From api/types.go
/**
 * RuleCheckResult shows if an IP is present in a rule's IPSet.
 */
export interface RuleCheckResult {
    rule_name: string;
    present_in_ipset: boolean;
    should_be_present: boolean;
    match_reason?: string; // e.g., "hostname acme.corp", "ipv4 1.2.3.0/24"
}

// From api/types.go
/**
 * SelfCheckResponse returns self-check results as a table.
 */
export interface SelfCheckResponse {
    checks: SelfCheckRow[];
}

// From api/types.go
/**
 * SelfCheckRow represents a single row in the self-check table.
 */
export interface SelfCheckRow {
    ipset: string; // IPSet name (empty for global checks)
    validation: string; // Type of check (e.g., "ipset", "ip_rule", "iptables")
    comment: string; // Explanation of what is being validated
    state: boolean; // true = pass (✓), false = fail (✗)
    message: string; // Detailed message
}

// From api/types.go
/**
 * ServiceControlRequest controls the keen-pbr service.
 */
export interface ServiceControlRequest {
    state: string; // "started", "stopped", "restarted"
}

// From api/types.go
/**
 * ServiceControlResponse returns the result of service control operation.
 */
export interface ServiceControlResponse {
    status: string;
    message?: string;
}

// From api/types.go
/**
 * ServiceInfo contains information about a service.
 */
export interface ServiceInfo {
    status: string; // "running", "stopped", "unknown"
    message?: string;
    config_hash?: string; // Hash of applied config (keen-pbr service only)
}

// From api/types.go
/**
 * SettingsResponse returns general settings.
 */
export interface SettingsResponse {
    general: GeneralConfig | null;
}

// From api/types.go
/**
 * StatusResponse returns system status information.
 */
export interface StatusResponse {
    version: VersionInfo;
    keenetic_version: string;
    services: Record<string, ServiceInfo> | null;
    current_config_hash: string;
    configuration_outdated: boolean;
    dns_servers: string[]; // Upstream DNS servers
}

// From api/types.go
/**
 * TracerouteCheckResponse returns traceroute results for a host.
 */
export interface TracerouteCheckResponse {
    host: string;
    resolved_ip?: string;
    success: boolean;
    hops?: TracerouteHop[];
    output?: string;
    error?: string;
}

// From api/types.go
/**
 * TracerouteHop represents a single hop in a traceroute.
 */
export interface TracerouteHop {
    hop: number;
    ip?: string;
    hostname?: string;
    rtt?: number; // milliseconds
}

// From config/validation.go
/**
 * ValidationError represents a single validation error with context
 */
export interface ValidationError {
    ItemName: string; // For lists/ipsets: the name of the item (e.g., "vpn1", "local-file")
    FieldPath: string; // Dot-notation field path (e.g., "general.fallback_dns", "routing.fwmark")
    Message: string; // Human-readable error message
}

// From config/validation.go
/**
 * ValidationErrors is a collection of validation errors
 */
export type ValidationErrors = ValidationError[];

// From api/types.go
/**
 * VersionInfo contains build version information.
 */
export interface VersionInfo {
    version: string;
    date: string;
    commit: string;
}

