#include <doctest/doctest.h>

#include "../src/firewall/firewall_counters.hpp"

#include <algorithm>

namespace keen_pbr3 {
namespace {

// A balance outbound "lb" over wan1 (0x100) and wan2 (0x200); its own mark is
// 0x900.  Comments are produced the way lowering produces them.
const OutboundMarkMap kMarks{{"lb", 0x900}, {"wan1", 0x100}, {"wan2", 0x200}, {"vpn", 0x300}};

FirewallRuleKey balance_key() {
  return FirewallRuleKey::compact("route.balance", "lb:rule0:v4");
}
FirewallRuleKey balance_key6() {
  return FirewallRuleKey::compact("route.balance", "lb:rule0:v6");
}
FirewallRuleKey skip_key() {
  return FirewallRuleKey::compact("prefilter.skip_marked_packets", "all");
}

FirewallPlan plan_with_balance() {
  FirewallPlan plan;
  for (const auto& key : {balance_key(), balance_key6()}) {
    FirewallRuleInstance rule;
    rule.key = key;
    rule.action = BalanceAction{0x900, {FirewallBalanceCandidate{0x100}, FirewallBalanceCandidate{0x200}}};
    plan.rules.push_back(rule);
  }
  FirewallRuleInstance mark;
  mark.key = FirewallRuleKey::compact("route.mark", "vpn");
  mark.action = MarkAction{0x300, 0xFF00};
  plan.rules.push_back(mark);
  return plan;
}

std::string save_v4() {
  const auto lb = balance_key().comment();
  const auto skip = skip_key().comment();
  return "# Generated by iptables-save v1.8.10 on Sat Oct 10 12:00:00 2026\n"
         "*mangle\n"
         ":PREROUTING ACCEPT [100:8000]\n"
         ":OUTPUT ACCEPT [10:800]\n"
         ":KeenPbrPrerouting - [0:0]\n"
         "[1500:120000] -A PREROUTING -j KeenPbrPrerouting\n"
         "[777:55555] -A PREROUTING -i br0 -m comment --comment \"foreign rule\" -j MARK --set-xmark 0x100/0xff00\n"
         "[900:70000] -A KeenPbrPrerouting -m mark ! --mark 0x0/0xffffffff -m comment --comment \"" + skip + "\" -j ACCEPT\n"
         "[5:300] -A KeenPbrPrerouting -m mark ! --mark 0x0/0xffffffff -m comment --comment \"" + skip + "\" -j ACCEPT\n"
         "[400:30000] -A KeenPbrPrerouting -m set --match-set kpbr_x dst -m mark --mark 0x0/0xff00 -m statistic --mode random --probability 0.50000000000 -m comment --comment \"" + lb + "\" -j MARK --set-xmark 0x100/0xff00\n"
         "[380:28000] -A KeenPbrPrerouting -m set --match-set kpbr_x dst -m mark --mark 0x0/0xff00 -m comment --comment \"" + lb + "\" -j MARK --set-xmark 0x200/0xff00\n"
         "[780:58000] -A KeenPbrPrerouting -m set --match-set kpbr_x dst -m comment --comment \"" + lb + "\" -j CONNMARK --save-mark --nfmask 0xff00 --ctmask 0xff00\n"
         "[780:58000] -A KeenPbrPrerouting -m set --match-set kpbr_x dst -m comment --comment \"" + lb + "\" -j RETURN\n"
         "COMMIT\n"
         "# Completed\n";
}

std::string save_v6() {
  const auto lb = balance_key6().comment();
  const auto skip = skip_key().comment();
  return "*mangle\n"
         ":PREROUTING ACCEPT [0:0]\n"
         ":KeenPbrPrerouting - [0:0]\n"
         "[12:960] -A KeenPbrPrerouting -m mark ! --mark 0x0/0xffffffff -m comment --comment \"" + skip + "\" -j ACCEPT\n"
         "[7:700] -A KeenPbrPrerouting -m mark --mark 0x0/0xff00 -m statistic --mode random --probability 0.50000000000 -m comment --comment \"" + lb + "\" -j MARK --set-xmark 0x100/0xff00\n"
         "[9:900] -A KeenPbrPrerouting -m mark --mark 0x0/0xff00 -m comment --comment \"" + lb + "\" -j MARK --set-xmark 0x200/0xff00\n"
         "COMMIT\n";
}

uint64_t classified(const FirewallCounters& counters, const std::string& candidate,
                    const std::string& family) {
  for (const auto& item : counters.balance_classifications) {
    if (item.outbound == "lb" && item.candidate == candidate && item.family == family) {
      return item.connections;
    }
  }
  return UINT64_MAX;
}

} // namespace

TEST_CASE("iptables-save -c parser extracts counters, comment, target and mark") {
  const auto rules = parse_iptables_save_counters(save_v4());
  // Chain declarations, COMMIT and comments are not rules.
  REQUIRE(rules.size() == 8);
  CHECK(rules[0].chain == "PREROUTING");
  CHECK(rules[0].comment.empty());
  CHECK(rules[0].target == "KeenPbrPrerouting");
  CHECK(rules[0].packets == 1500);
  CHECK(rules[0].bytes == 120000);
  CHECK(rules[1].comment == "foreign rule");
  CHECK(rules[1].mark_value == 0x100U);
  CHECK(rules[1].table == "mangle");
  CHECK(rules[4].packets == 400);
  CHECK(rules[4].bytes == 30000);
  CHECK(rules[4].target == "MARK");
  CHECK(rules[4].mark_value == 0x100U);
  CHECK(rules[4].comment == balance_key().comment());
  CHECK(rules[6].target == "CONNMARK");
  CHECK_FALSE(rules[6].mark_value.has_value());
  CHECK(rules[7].target == "RETURN");
}

TEST_CASE("counter parser skips malformed counters and reads quoted comments") {
  const auto rules = parse_iptables_save_counters(
      "*mangle\n[bad:1] -A X -j ACCEPT\n[1:2] -A Y -m comment --comment \"a b\" -j MARK --set-mark 0x5\n");
  REQUIRE(rules.size() == 1);
  CHECK(rules[0].comment == "a b");
  CHECK(rules[0].mark_value == 5U);
  CHECK(rules[0].packets == 1);
}

TEST_CASE("counter index maps balance comments to the balance outbound") {
  const auto index = build_firewall_counter_index(plan_with_balance(), kMarks);
  CHECK(index.balance_comment_outbound.size() == 2);
  CHECK(index.balance_comment_outbound.at(balance_key().comment()) == "lb");
  CHECK(index.mark_outbound.at(0x200) == "wan2");
}

TEST_CASE("candidate classifications and skip_marked are aggregated per family") {
  const auto index = build_firewall_counter_index(plan_with_balance(), kMarks);
  FirewallCounters counters;
  aggregate_firewall_counters(parse_iptables_save_counters(save_v4()), "ipv4", index, counters);
  aggregate_firewall_counters(parse_iptables_save_counters(save_v6()), "ipv6", index, counters);

  CHECK(counters.balance_classifications.size() == 4);
  CHECK(classified(counters, "wan1", "ipv4") == 400);
  CHECK(classified(counters, "wan2", "ipv4") == 380);
  CHECK(classified(counters, "wan1", "ipv6") == 7);
  CHECK(classified(counters, "wan2", "ipv6") == 9);
  // The skip rule exists in two chains; the foreign MARK rule is not counted.
  CHECK(counters.skip_marked_packets.at("ipv4") == 905);
  CHECK(counters.skip_marked_packets.at("ipv6") == 12);
}

TEST_CASE("counters ignore balance comments that are not in the plan") {
  FirewallCounters counters;
  aggregate_firewall_counters(parse_iptables_save_counters(save_v4()), "ipv4", {}, counters);
  CHECK(counters.balance_classifications.empty());
  CHECK(counters.skip_marked_packets.at("ipv4") == 905);
}

TEST_CASE("collect_iptables_counters reads each family once and omits unreadable ones") {
  const auto index = build_firewall_counter_index(plan_with_balance(), kMarks);
  std::vector<std::vector<std::string>> calls;
  const CommandRunner runner = [&](const std::vector<std::string>& args) {
    calls.push_back(args);
    if (args[0] == "iptables-save") return CommandResult{save_v4(), 0, false};
    return CommandResult{"", 1, false};
  };
  const auto counters = collect_iptables_counters(runner, index, true, {});
  REQUIRE(calls.size() == 2);
  CHECK(calls[0] == std::vector<std::string>{"iptables-save", "-c", "-t", "mangle"});
  CHECK(calls[1] == std::vector<std::string>{"ip6tables-save", "-c", "-t", "mangle"});
  CHECK(counters.skip_marked_packets.count("ipv6") == 0);
  CHECK(classified(counters, "wan1", "ipv4") == 400);

  calls.clear();
  (void)collect_iptables_counters(runner, index, false, RawPreroutingMode{true, false});
  REQUIRE(calls.size() == 2);
  CHECK(calls[1][3] == "raw");
}

TEST_CASE("FirewallCounterCache reuses a read within its lifetime per generation") {
  FirewallCounterCache cache(std::chrono::seconds{60});
  int reads = 0;
  const auto read = [&]() {
    ++reads;
    FirewallCounters counters;
    counters.skip_marked_packets["ipv4"] = static_cast<uint64_t>(reads);
    return counters;
  };
  int a = 0;
  int b = 0;
  CHECK(cache.get(&a, read).skip_marked_packets.at("ipv4") == 1);
  CHECK(cache.get(&a, read).skip_marked_packets.at("ipv4") == 1);
  CHECK(reads == 1);
  CHECK(cache.get(&b, read).skip_marked_packets.at("ipv4") == 2);
}

} // namespace keen_pbr3
