#!/bin/sh

# Essential paths
KEEN_PBR_CONF="/opt/etc/keen-pbr/keen-pbr.conf"

echo "keen-pbr installation"
echo "------------------------"

if [ -f "${KEEN_PBR_CONF}" ]; then
	echo "Existing keen-pbr.conf found, upgrading it. Old config will be backed up to 'keen-pbr.conf.before-update'"
	cp "${KEEN_PBR_CONF}" "${KEEN_PBR_CONF}.before-update"
	keen-pbr upgrade-config || echo "keen-pbr config upgrade failed"
fi

echo "Installation complete!"
echo "Next steps:"
echo "1. Open http://my.keenetic.net:8080 (or http://<router-ip>:8080) to access keen-pbr web interface"
echo "2. Configure your Lists and Rules"
echo "3. Restart keen-pbr service"
echo "4. Check DNS and Routing status on keen-pbr Dashboard"
echo ""

exit 0
