#!/bin/sh

# Essential paths
KEEN_PBR_CONF="/opt/etc/keen-pbr/keen-pbr.conf"

echo "keen-pbr installation"
echo "------------------------"

if [ -f "${KEEN_PBR_CONF}" ]; then
	echo "Existing keen-pbr.conf found, upgrading it. Old config will be backed up to 'keen-pbr.conf.before-update'"
	cp "${KEEN_PBR_CONF}" "${KEEN_PBR_CONF}.before-update"
	keen-pbr upgrade-config || echo "keen-pbr config upgrade failed"
fi

echo "Installation complete!"
echo "Please make sure to:"
echo "1. Configure ${KEEN_PBR_CONF}"
echo "2. (recommended) Install dnscrypt-proxy2 and configure it"
echo "3. Run the following command: keen-pbr download"
echo "4. Enable opkg dns-override"
echo "5. Restart OPKG"
echo ""

exit 0
