#!/bin/sh

. /opt/etc/keen-pbr/defaults

ENABLED=yes
PROCS=$(basename "$KEEN_PBR")
ARGS="-config $CONFIG service"
PREARGS=""
DESC="keen-pbr"
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

log() {
    logger -t "keen-pbr" "$1"
    echo -e "${ansi_blue}[keen-pbr]${ansi_white} $1${ansi_std}" >&2
}

enable_hwnat() {
    log "Enabling HW NAT..."
    sysctl -w net.ipv4.netfilter.ip_conntrack_fastnat=1 2>/dev/null || true
    sysctl -w net.netfilter.nf_conntrack_fastnat=1 2>/dev/null || true
}

disable_hwnat() {
    log "Disabling HW NAT..."
    sysctl -w net.ipv4.netfilter.ip_conntrack_fastnat=0 2>/dev/null || true
    sysctl -w net.netfilter.nf_conntrack_fastnat=0 2>/dev/null || true
}

PRECMD="disable_hwnat"

. /opt/etc/init.d/rc.func

if [ "$1" = "stop" ] || [ "$1" = "kill" ]; then
    enable_hwnat
fi
