#pragma once

#include <cstdint>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

#include "../util/traced_mutex.hpp"

namespace keen_pbr3 {

class NetlinkError : public std::runtime_error {
public:
    using std::runtime_error::runtime_error;
};

enum class RouteType {
    unicast,
    blackhole,
    unreachable
};

// Reserved RTPROT value for routes generated by keen-pbr. It is deliberately
// distinct from kernel, boot, static and dhcp route protocols.
#ifndef KEEN_PBR_ROUTE_PROTOCOL
#define KEEN_PBR_ROUTE_PROTOCOL 186
#endif
constexpr uint8_t KEEN_PBR_GENERATED_ROUTE_PROTOCOL = KEEN_PBR_ROUTE_PROTOCOL;

// Represents a route to install in the kernel
struct RouteSpec {
    std::string destination;    // IP/CIDR (e.g., "10.0.0.0/8") or "default"
    uint32_t table{0};          // Routing table ID (0 = main)
    std::optional<std::string> interface;   // Output interface name
    std::optional<std::string> gateway;     // Next-hop gateway IP
    bool blackhole{false};      // If true, create a blackhole route
    bool unreachable{false};    // If true, create an unreachable route
    int family{0};              // AF_INET or AF_INET6 (0 = auto-detect)
    uint32_t metric{0};         // Route metric/priority (0 = kernel default)
    uint8_t protocol{KEEN_PBR_GENERATED_ROUTE_PROTOCOL}; // rtm_protocol ownership marker
};

enum class RouteAddResult {
    Created,
    AlreadyPresent,
};

class RouteNetlinkOperations {
public:
    virtual ~RouteNetlinkOperations() = default;
    virtual RouteAddResult add_route(const RouteSpec& spec) = 0;
    virtual void delete_route(const RouteSpec& spec) = 0;
};

// Represents a policy routing rule (ip rule)
struct RuleSpec {
    uint32_t fwmark{0};         // Firewall mark to match
    uint32_t fwmask{0xFFFFFFFF}; // Firewall mark mask
    uint32_t table{0};          // Routing table to use
    uint32_t priority{0};       // Rule priority (lower = higher priority)
    int family{0};              // AF_INET or AF_INET6 (0 = both)
};

enum class RuleAddResult {
    Created,
    AlreadyPresent,
};

class RuleNetlinkOperations {
public:
    virtual ~RuleNetlinkOperations() = default;
    virtual RuleAddResult add_rule_for_family(const RuleSpec& spec, int family) = 0;
    virtual void delete_rule_for_family(const RuleSpec& spec, int family) = 0;
};

// A route dumped from the kernel (read-only snapshot)
struct DumpedRoute {
    std::string destination;            // "default" for 0/0, else "x.x.x.x/N"
    uint32_t table{0};                  // Routing table ID
    std::optional<std::string> interface;  // Output interface name (if any)
    std::optional<std::string> gateway;    // Next-hop gateway IP (if any)
    bool blackhole{false};              // True if route type is RTN_BLACKHOLE
    bool unreachable{false};           // True if route type is RTN_UNREACHABLE
    int family{0};                      // AF_INET or AF_INET6
    uint32_t metric{0};                 // Route metric/priority
    uint8_t protocol{0};                // rtm_protocol ownership marker
};

// A policy rule dumped from the kernel (read-only snapshot)
struct DumpedRule {
    uint32_t priority{0};
    uint32_t fwmark{0};
    uint32_t fwmask{0};
    uint32_t table{0};
    int family{0};              // AF_INET or AF_INET6
};

// A network interface dumped from the kernel (read-only snapshot)
struct DumpedInterface {
    std::string name;                   // Interface name (e.g. "eth0")
    bool admin_up{false};              // True when IFF_UP is set
    std::optional<std::string> oper_state; // Kernel operstate label when available
    std::optional<bool> carrier;       // Link carrier state when reported by kernel
    std::vector<std::string> ipv4_addresses; // IPv4 addresses in CIDR form
    std::vector<std::string> ipv6_addresses; // IPv6 addresses in CIDR form
};

// The complete netlink surface required by a state reconciler.  Keeping this
// separate from NetlinkManager makes ownership decisions unit-testable.
class RoutingNetlinkOperations : public RouteNetlinkOperations,
                                 public RuleNetlinkOperations {
public:
    virtual std::vector<DumpedRoute> dump_routes_in_table(uint32_t table_id,
                                                            int family = 0) = 0;
    virtual std::vector<DumpedRule> dump_policy_rules(int family = 0) = 0;
};

// Low-level netlink route and policy rule management via libnl
class NetlinkManager : public RoutingNetlinkOperations {
public:
    NetlinkManager();
    ~NetlinkManager();

    // Non-copyable, non-movable (owns netlink socket)
    NetlinkManager(const NetlinkManager&) = delete;
    NetlinkManager& operator=(const NetlinkManager&) = delete;
    NetlinkManager(NetlinkManager&&) = delete;
    NetlinkManager& operator=(NetlinkManager&&) = delete;

    // Route operations
    RouteAddResult add_route(const RouteSpec& spec) override;
    void delete_route(const RouteSpec& spec) override;
    void flush_routes_in_table(uint32_t table_id, int family = 0);

    // Policy rule operations
    RuleAddResult add_rule_for_family(const RuleSpec& spec, int family) override;
    void delete_rule_for_family(const RuleSpec& spec, int family) override;

    // Dump all routes in a specific routing table from the kernel.
    // family: 0 (AF_UNSPEC) to get both IPv4 and IPv6 routes.
    std::vector<DumpedRoute> dump_routes_in_table(uint32_t table_id,
                                                   int family = 0) override;

    // Dump all policy rules from the kernel.
    // family: 0 (AF_UNSPEC) to get both IPv4 and IPv6 rules.
    std::vector<DumpedRule> dump_policy_rules(int family = 0) override;

    // Dump all network interfaces from the kernel with best-effort live detail.
    std::vector<DumpedInterface> dump_interfaces();

private:
    struct Impl;
    std::unique_ptr<Impl> impl_;
    mutable TracedMutex mutex_;
};

} // namespace keen_pbr3
