#include "dnsmasq_gen.hpp"
#include "../crypto/md5.hpp"
#include "../log/logger.hpp"

#include <chrono>
#include <functional>
#include <set>

namespace keen_pbr3 {

namespace {

static constexpr const char* kDnsProbeZone = "check.keen.pbr";
static constexpr size_t kBatchSize = 50;
static constexpr size_t kMaxDnsmasqRowLength = 1024;
static constexpr size_t kMaxDomainNameLength = 255;
static constexpr size_t kIpsetPrefixLen = sizeof("ipset=") - 1;
static constexpr size_t kNftsetPrefixLen = sizeof("nftset=") - 1;
static constexpr size_t kRebindPrefixLen = sizeof("rebind-domain-ok=") - 1;
static constexpr size_t kServerPrefixLen = sizeof("server=") - 1;
static constexpr const char* kNftSetPrefix = "/4#inet#KeenPbrTable#";
static constexpr const char* kNftSetMiddle = ",6#inet#KeenPbrTable#";
static constexpr size_t kNftSetPrefixLen = sizeof("/4#inet#KeenPbrTable#") - 1;
static constexpr size_t kNftSetMiddleLen = sizeof(",6#inet#KeenPbrTable#") - 1;

} // anonymous namespace

DnsmasqGenerator::DnsmasqGenerator(const DnsServerRegistry& dns_registry,
                                   ListStreamer& list_streamer,
                                   const RouteConfig& route_config,
                                   const DnsConfig& dns_config,
                                   const std::map<std::string, ListConfig>& lists,
                                   ResolverType resolver_type,
                                   std::string hash_version)
    : dns_registry_(dns_registry),
      list_streamer_(list_streamer),
      route_config_(route_config),
      dns_config_(dns_config),
      lists_(lists),
      resolver_type_(resolver_type),
      hash_version_(std::move(hash_version)) {}

std::string DnsmasqGenerator::compute_config_hash() {
    crypto::detail::MD5State md5;
    generate_directives(
        nullptr,
        [&md5](const std::string& line) {
            md5.update(reinterpret_cast<const uint8_t*>(line.data()), line.size());
            static constexpr char newline = '\n';
            md5.update(reinterpret_cast<const uint8_t*>(&newline), 1);
        });
    return crypto::digest_to_hex(md5.digest());
}

std::string DnsmasqGenerator::compute_config_hash(
    const DnsServerRegistry& dns_registry,
    ListStreamer& list_streamer,
    const RouteConfig& route_config,
    const DnsConfig& dns_config,
    const std::map<std::string, ListConfig>& lists,
    std::string hash_version)
{
    return DnsmasqGenerator(dns_registry, list_streamer, route_config,
                            dns_config, lists, ResolverType::DNSMASQ_IPSET,
                            std::move(hash_version))
           .compute_config_hash();
}

void DnsmasqGenerator::generate_directives(
    std::ostream* out,
    const std::function<void(const std::string&)>& hash_record_callback) {
    if (hash_record_callback) {
        hash_record_callback("version|" + hash_version_);
    }

    if (out != nullptr) {
        const char* resolver_name = (resolver_type_ == ResolverType::DNSMASQ_IPSET)
            ? "dnsmasq-ipset" : "dnsmasq-nftset";
        *out << "# Generated by keen-pbr (" << resolver_name << ") - do not edit manually\n\n";
        *out << "address=/use-application-dns.net/\n\n";
    }

    if (dns_config_.dns_test_server.has_value()) {
        const auto parsed = parse_dns_address_str(dns_config_.dns_test_server->listen);
        if (hash_record_callback) {
            hash_record_callback(
                "probe-server|" + parsed.ip + "|" + std::to_string(parsed.port));
        }
        if (out != nullptr) {
            *out << "rebind-domain-ok=keen.pbr\n";
            *out << "server=/" << kDnsProbeZone << "/" << parsed.ip << "#" << parsed.port << "\n\n";
        }
    }

    size_t fallback_index = 0;
    for (const DnsServerConfig* server : dns_registry_.fallback_servers()) {
        if (hash_record_callback) {
            hash_record_callback(
                "fallback-server|" + std::to_string(fallback_index) +
                "|" + server->resolved_ip +
                "|" + std::to_string(server->port));
        }
        ++fallback_index;
        if (out != nullptr) {
            *out << "server=" << server->resolved_ip;
            if (server->port != 53) {
                *out << "#" << server->port;
            }
            *out << "\n";
        }
    }
    if (out != nullptr && dns_config_.fallback.has_value() && !dns_config_.fallback->empty()) {
        *out << "\n";
    }

    std::set<std::string> ipset_lists;
    for (const auto& rule : route_config_.rules.value_or(std::vector<RouteRule>{})) {
        if (!route_rule_enabled(rule)) {
            continue;
        }
        for (const auto& list_name : route_rule_lists(rule)) {
            ipset_lists.insert(list_name);
        }
    }

    std::map<std::string, std::string> dns_list_servers;
    std::map<std::string, bool> dns_list_allow_rebind;
    for (const auto& rule : dns_config_.rules.value_or(std::vector<DnsRule>{})) {
        if (!dns_rule_enabled(rule)) {
            continue;
        }
        for (const auto& list_name : rule.list) {
            if (dns_list_servers.find(list_name) == dns_list_servers.end()) {
                dns_list_servers[list_name] = rule.server;
                dns_list_allow_rebind[list_name] =
                    rule.allow_domain_rebinding.value_or(false);
            }
        }
    }

    std::set<std::string> all_lists;
    all_lists.insert(ipset_lists.begin(), ipset_lists.end());
    for (const auto& [list_name, _] : dns_list_servers) {
        all_lists.insert(list_name);
    }

    for (const auto& list_name : all_lists) {
        auto list_cfg_it = lists_.find(list_name);
        if (list_cfg_it == lists_.end()) {
            continue;
        }

        const bool needs_ipset = ipset_lists.count(list_name) > 0;

        std::string dns_ip;
        uint16_t dns_port = 53;
        auto dns_it = dns_list_servers.find(list_name);
        if (dns_it != dns_list_servers.end()) {
            const DnsServerConfig* server = dns_registry_.get_server(dns_it->second);
            if (server) {
                dns_ip = server->resolved_ip;
                dns_port = server->port;
            }
        }

        const bool allow_domain_rebinding =
            dns_list_allow_rebind.find(list_name) != dns_list_allow_rebind.end()
            && dns_list_allow_rebind[list_name];

        std::string server_addr = dns_ip;
        if (!server_addr.empty() && dns_port != 53) {
            server_addr += "#" + std::to_string(dns_port);
        }

        bool wrote_list_header = false;
        auto ensure_list_header = [&]() {
            if (out != nullptr && !wrote_list_header) {
                *out << "# List: " << list_name << "\n";
                wrote_list_header = true;
            }
        };

        struct BatchState {
            bool enabled{false};
            std::string directive_name;
            size_t prefix_len{0};
            size_t suffix_len{0};
            size_t count{0};
            std::string domain_path;
            std::function<void(std::ostream&, const std::string&)> emit_line;
        };

        auto flush_batch = [&](BatchState& batch) {
            if (out == nullptr || !batch.enabled || batch.count == 0) {
                return;
            }
            batch.emit_line(*out, batch.domain_path);
            batch.domain_path.clear();
            batch.count = 0;
        };

        auto push_batch = [&](BatchState& batch, std::string_view domain) {
            if (out == nullptr || !batch.enabled) {
                return;
            }

            std::string next_chunk = batch.domain_path;
            next_chunk += "/";
            next_chunk += domain;
            if (batch.count >= kBatchSize ||
                batch.prefix_len + next_chunk.size() + batch.suffix_len > kMaxDnsmasqRowLength) {
                flush_batch(batch);
                next_chunk.assign("/");
                next_chunk += domain;
                if (batch.prefix_len + next_chunk.size() + batch.suffix_len >
                    kMaxDnsmasqRowLength) {
                    Logger::instance().warn(
                        "Skipping domain '{}' from list '{}': {} directive would exceed {} chars",
                        domain, list_name, batch.directive_name, kMaxDnsmasqRowLength);
                    return;
                }
            }

            batch.domain_path = std::move(next_chunk);
            ++batch.count;
        };

        BatchState ipset_batch;
        if (out != nullptr && needs_ipset) {
            const std::string set4 = ipset_name_v4(list_name);
            const std::string set6 = ipset_name_v6(list_name);
            if (resolver_type_ == ResolverType::DNSMASQ_IPSET) {
                ipset_batch.enabled = true;
                ipset_batch.directive_name = "ipset";
                ipset_batch.prefix_len = kIpsetPrefixLen;
                ipset_batch.suffix_len = 1 + set4.size() + 1 + set6.size();
                ipset_batch.emit_line =
                    [set4, set6](std::ostream& stream, const std::string& domain_path) {
                        stream << "ipset=" << domain_path << "/" << set4 << "," << set6 << "\n";
                    };
            } else {
                ipset_batch.enabled = true;
                ipset_batch.directive_name = "nftset";
                ipset_batch.prefix_len = kNftsetPrefixLen;
                ipset_batch.suffix_len =
                    kNftSetPrefixLen + set4.size() + kNftSetMiddleLen + set6.size();
                ipset_batch.emit_line =
                    [set4, set6](std::ostream& stream, const std::string& domain_path) {
                        stream << "nftset=" << domain_path
                               << kNftSetPrefix << set4
                               << kNftSetMiddle << set6 << "\n";
                    };
            }
        }

        BatchState rebind_batch;
        if (out != nullptr && allow_domain_rebinding) {
            rebind_batch.enabled = true;
            rebind_batch.directive_name = "rebind-domain-ok";
            rebind_batch.prefix_len = kRebindPrefixLen;
            rebind_batch.suffix_len = 1;
            rebind_batch.emit_line = [](std::ostream& stream, const std::string& domain_path) {
                stream << "rebind-domain-ok=" << domain_path << "/\n";
            };
        }

        BatchState server_batch;
        if (out != nullptr && !server_addr.empty()) {
            server_batch.enabled = true;
            server_batch.directive_name = "server";
            server_batch.prefix_len = kServerPrefixLen;
            server_batch.suffix_len = 1 + server_addr.size();
            server_batch.emit_line =
                [server_addr](std::ostream& stream, const std::string& domain_path) {
                    stream << "server=" << domain_path << "/" << server_addr << "\n";
                };
        }

        FunctionalVisitor collector([&](EntryType type, std::string_view entry) {
            if (type != EntryType::Domain) {
                return;
            }

            std::string bare = strip_wildcard(std::string(entry));
            if (bare.empty()) {
                return;
            }
            if (bare.size() > kMaxDomainNameLength) {
                Logger::instance().warn(
                    "Skipping invalid domain '{}' from list '{}': length {} exceeds {}",
                    bare, list_name, bare.size(), kMaxDomainNameLength);
                return;
            }

            std::string flags;
            if (needs_ipset) {
                flags = "route";
            }
            if (allow_domain_rebinding) {
                if (!flags.empty()) {
                    flags += ",";
                }
                flags += "rebind";
            }
            if (!dns_ip.empty()) {
                if (!flags.empty()) {
                    flags += ",";
                }
                flags += "server";
            }
            if (flags.empty()) {
                return;
            }

            if (hash_record_callback) {
                hash_record_callback(
                    "domain|" + list_name + "|" + bare + "|" + flags +
                    (dns_ip.empty() ? std::string{} : "|" + dns_ip + "|" + std::to_string(dns_port)));
            }

            ensure_list_header();
            push_batch(ipset_batch, bare);
            push_batch(rebind_batch, bare);
            push_batch(server_batch, bare);
        });
        list_streamer_.stream_list(list_name, list_cfg_it->second, collector);

        flush_batch(ipset_batch);
        flush_batch(rebind_batch);
        flush_batch(server_batch);
        if (out != nullptr && wrote_list_header) {
            *out << "\n";
        }
    }
}

void DnsmasqGenerator::generate(std::ostream& out) {
    crypto::detail::MD5State md5;
    generate_directives(
        &out,
        [&md5](const std::string& line) {
            md5.update(reinterpret_cast<const uint8_t*>(line.data()), line.size());
            static constexpr char newline = '\n';
            md5.update(reinterpret_cast<const uint8_t*>(&newline), 1);
        });
    const std::string hash = crypto::digest_to_hex(md5.digest());
    const auto now_ts = std::chrono::duration_cast<std::chrono::seconds>(
        std::chrono::system_clock::now().time_since_epoch()).count();
    out << "txt-record=config-hash.keen.pbr," << now_ts << "|" << hash << "\n";
}

ResolverType DnsmasqGenerator::parse_resolver_type(const std::string& s) {
    if (s == "dnsmasq-ipset")  return ResolverType::DNSMASQ_IPSET;
    if (s == "dnsmasq-nftset") return ResolverType::DNSMASQ_NFTSET;
    throw std::invalid_argument("Unknown resolver type: " + s);
}

std::string DnsmasqGenerator::strip_wildcard(const std::string& domain) {
    if (domain.size() > 2 && domain[0] == '*' && domain[1] == '.') {
        return domain.substr(2);
    }
    return domain;
}

} // namespace keen_pbr3
