#include "dnsmasq_gen.hpp"

#include <fstream>
#include <set>
#include <sstream>
#include <stdexcept>

namespace keen_pbr3 {

DnsmasqGenerator::DnsmasqGenerator(const DnsRouter& dns_router,
                                   const ListManager& list_manager,
                                   const RouteConfig& route_config,
                                   const DnsConfig& dns_config)
    : dns_router_(dns_router),
      list_manager_(list_manager),
      route_config_(route_config),
      dns_config_(dns_config) {}

std::string DnsmasqGenerator::generate() const {
    std::ostringstream out;
    out << "# Generated by keen-pbr3 - do not edit manually\n\n";

    // Collect all list names referenced in route rules that need ipset population.
    // Each route rule's lists map to an ipset set name.
    std::set<std::string> ipset_lists;
    for (const auto& rule : route_config_.rules) {
        // Skip rules with skip action - they don't need ipsets
        if (std::holds_alternative<SkipAction>(rule.action)) {
            continue;
        }
        for (const auto& list_name : rule.lists) {
            ipset_lists.insert(list_name);
        }
    }

    // Collect all list names referenced in DNS rules for server directives.
    // Map: list_name -> dns server tag
    std::map<std::string, std::string> dns_list_servers;
    for (const auto& rule : dns_config_.rules) {
        for (const auto& list_name : rule.lists) {
            // First rule wins for a given list (same as DnsRouter matching)
            if (dns_list_servers.find(list_name) == dns_list_servers.end()) {
                dns_list_servers[list_name] = rule.server;
            }
        }
    }

    // Gather all unique list names that need processing
    std::set<std::string> all_lists;
    all_lists.insert(ipset_lists.begin(), ipset_lists.end());
    for (const auto& [list_name, _] : dns_list_servers) {
        all_lists.insert(list_name);
    }

    // For each list, iterate domains and generate directives
    for (const auto& list_name : all_lists) {
        const ParsedList* list = list_manager_.get(list_name);
        if (!list || list->domains.empty()) {
            continue;
        }

        out << "# List: " << list_name << "\n";

        bool needs_ipset = ipset_lists.count(list_name) > 0;
        std::string ipset = needs_ipset ? ipset_name(list_name) : "";

        // Determine DNS server IP for this list (if a DNS rule maps it)
        std::string dns_ip;
        auto dns_it = dns_list_servers.find(list_name);
        if (dns_it != dns_list_servers.end()) {
            const DnsServerConfig* server = dns_router_.get_server(dns_it->second);
            if (server && server->type == DnsServerType::PlainIP) {
                dns_ip = server->resolved_ip;
            }
        }

        // Use a set to avoid duplicate domain entries
        std::set<std::string> seen_domains;

        for (const auto& domain : list->domains) {
            std::string bare = strip_wildcard(domain);
            if (bare.empty() || !seen_domains.insert(bare).second) {
                continue;
            }

            // Generate ipset directive: ipset=/domain/setname_ip,setname_net
            if (needs_ipset) {
                out << "ipset=/" << bare << "/" << ipset << "_ip,"
                    << ipset << "_net\n";
            }

            // Generate server directive: server=/domain/dns-ip
            if (!dns_ip.empty()) {
                out << "server=/" << bare << "/" << dns_ip << "\n";
            }
        }

        out << "\n";
    }

    return out.str();
}

void DnsmasqGenerator::write(const std::filesystem::path& output_path) const {
    // Ensure parent directory exists
    if (output_path.has_parent_path()) {
        std::filesystem::create_directories(output_path.parent_path());
    }

    std::ofstream file(output_path);
    if (!file.is_open()) {
        throw std::runtime_error(
            "Failed to open dnsmasq config file for writing: " +
            output_path.string());
    }

    file << generate();

    if (!file.good()) {
        throw std::runtime_error(
            "Failed to write dnsmasq config file: " + output_path.string());
    }
}

std::string DnsmasqGenerator::ipset_name(const std::string& list_name) {
    // The ipset set name matches the name used by the firewall backend.
    // Convention: list name is used directly as the base set name.
    return list_name;
}

std::string DnsmasqGenerator::strip_wildcard(const std::string& domain) {
    // *.example.com -> example.com
    if (domain.size() > 2 && domain[0] == '*' && domain[1] == '.') {
        return domain.substr(2);
    }
    return domain;
}

} // namespace keen_pbr3
