#include "dnsmasq_gen.hpp"
#include "../crypto/md5.hpp"

#include <set>

namespace keen_pbr3 {

static constexpr size_t BATCH_SIZE = 50;

DnsmasqGenerator::DnsmasqGenerator(const DnsServerRegistry& dns_registry,
                                   ListStreamer& list_streamer,
                                   const RouteConfig& route_config,
                                   const DnsConfig& dns_config,
                                   const std::map<std::string, ListConfig>& lists,
                                   ResolverType resolver_type)
    : dns_registry_(dns_registry),
      list_streamer_(list_streamer),
      route_config_(route_config),
      dns_config_(dns_config),
      lists_(lists),
      resolver_type_(resolver_type) {}

void DnsmasqGenerator::for_each_ipset_domain(
    std::function<void(const std::string& domain,
                       const std::string& list_name)> callback)
{
    // Collect all list names referenced in route rules that need ipset population.
    std::set<std::string> ipset_lists;
    for (const auto& rule : route_config_.rules.value_or(std::vector<RouteRule>{})) {
        for (const auto& list_name : rule.list) {
            ipset_lists.insert(list_name);
        }
    }

    std::set<std::string> domains;

    for (const auto& list_name : ipset_lists) {
        auto list_cfg_it = lists_.find(list_name);
        if (list_cfg_it == lists_.end()) continue;

        domains.clear();
        FunctionalVisitor collector([&](EntryType type, std::string_view entry) {
            if (type == EntryType::Domain) {
                std::string bare = strip_wildcard(std::string(entry));
                if (!bare.empty()) {
                    domains.insert(std::move(bare));
                }
            }
        });
        list_streamer_.stream_list(list_name, list_cfg_it->second, collector);

        for (const auto& domain : domains) {
            callback(domain, list_name);
        }
    }
}

std::string DnsmasqGenerator::compute_config_hash() {
    return compute_config_hash(list_streamer_, route_config_, lists_);
}

std::string DnsmasqGenerator::compute_config_hash(
    ListStreamer& list_streamer,
    const RouteConfig& route_config,
    const std::map<std::string, ListConfig>& lists)
{
    // Collect all list names referenced in route rules that need ipset population.
    std::set<std::string> ipset_lists;
    for (const auto& rule : route_config.rules.value_or(std::vector<RouteRule>{})) {
        for (const auto& list_name : rule.list) {
            ipset_lists.insert(list_name);
        }
    }

    std::string hash_input;
    for (const auto& list_name : ipset_lists) {
        auto list_cfg_it = lists.find(list_name);
        if (list_cfg_it == lists.end()) continue;

        std::set<std::string> domains;
        FunctionalVisitor collector([&](EntryType type, std::string_view entry) {
            if (type == EntryType::Domain) {
                std::string bare = strip_wildcard(std::string(entry));
                if (!bare.empty()) {
                    domains.insert(std::move(bare));
                }
            }
        });
        list_streamer.stream_list(list_name, list_cfg_it->second, collector);

        for (const auto& domain : domains) {
            hash_input += domain + "/" + ipset_name_v4(list_name) + "/" + ipset_name_v6(list_name) + "\n";
        }
    }

    return crypto::md5_hex(hash_input);
}

void DnsmasqGenerator::generate(std::ostream& out) {
    const char* resolver_name = (resolver_type_ == ResolverType::DNSMASQ_IPSET)
        ? "dnsmasq-ipset" : "dnsmasq-nftset";
    out << "# Generated by keen-pbr3 (" << resolver_name << ") - do not edit manually\n\n";

    // Collect all list names referenced in route rules that need ipset population.
    std::set<std::string> ipset_lists;
    for (const auto& rule : route_config_.rules.value_or(std::vector<RouteRule>{})) {
        for (const auto& list_name : rule.list) {
            ipset_lists.insert(list_name);
        }
    }

    // Collect all list names referenced in DNS rules for server directives.
    // Map: list_name -> dns server tag
    std::map<std::string, std::string> dns_list_servers;
    for (const auto& rule : dns_config_.rules.value_or(std::vector<DnsRule>{})) {
        for (const auto& list_name : rule.list) {
            if (dns_list_servers.find(list_name) == dns_list_servers.end()) {
                dns_list_servers[list_name] = rule.server;
            }
        }
    }

    // Gather all unique list names that need processing
    std::set<std::string> all_lists;
    all_lists.insert(ipset_lists.begin(), ipset_lists.end());
    for (const auto& [list_name, _] : dns_list_servers) {
        all_lists.insert(list_name);
    }

    // Compute config hash from canonical ipset domain mapping
    const std::string config_hash = compute_config_hash();
    out << "txt-record=config-hash.keen.pbr," << config_hash << "\n\n";

    // Domain-collecting visitor with dedup set, reused across lists
    std::set<std::string> domains;

    for (const auto& list_name : all_lists) {
        // Find the list config
        auto list_cfg_it = lists_.find(list_name);
        if (list_cfg_it == lists_.end()) {
            continue;
        }

        // Collect unique domains by streaming through a visitor
        domains.clear();
        FunctionalVisitor collector([&](EntryType type, std::string_view entry) {
            if (type == EntryType::Domain) {
                std::string bare = strip_wildcard(std::string(entry));
                if (!bare.empty()) {
                    domains.insert(std::move(bare));
                }
            }
        });
        list_streamer_.stream_list(list_name, list_cfg_it->second, collector);

        if (domains.empty()) continue;

        out << "# List: " << list_name << "\n";

        bool needs_ipset = ipset_lists.count(list_name) > 0;

        // Determine DNS server IP for this list (if a DNS rule maps it)
        std::string dns_ip;
        auto dns_it = dns_list_servers.find(list_name);
        if (dns_it != dns_list_servers.end()) {
            const DnsServerConfig* server = dns_registry_.get_server(dns_it->second);
            if (server) {
                dns_ip = server->resolved_ip;
            }
        }

        // Output domains in batches of ~BATCH_SIZE per directive line
        auto it = domains.begin();
        while (it != domains.end()) {
            std::string domain_path;
            size_t count = 0;
            while (it != domains.end() && count < BATCH_SIZE) {
                domain_path += "/" + *it;
                ++it;
                ++count;
            }

            if (needs_ipset) {
                const std::string set4 = ipset_name_v4(list_name);
                const std::string set6 = ipset_name_v6(list_name);
                if (resolver_type_ == ResolverType::DNSMASQ_IPSET) {
                    out << "ipset=" << domain_path << "/" << set4 << "," << set6 << "\n";
                } else {
                    out << "nftset=" << domain_path
                        << "/4#inet#KeenPbrTable#" << set4
                        << ",6#inet#KeenPbrTable#" << set6 << "\n";
                }
            }
            if (!dns_ip.empty()) {
                out << "server=" << domain_path << "/" << dns_ip << "\n";
            }
        }

        out << "\n";
    }
}


ResolverType DnsmasqGenerator::parse_resolver_type(const std::string& s) {
    if (s == "dnsmasq-ipset")  return ResolverType::DNSMASQ_IPSET;
    if (s == "dnsmasq-nftset") return ResolverType::DNSMASQ_NFTSET;
    throw std::invalid_argument("Unknown resolver type: " + s);
}

std::string DnsmasqGenerator::strip_wildcard(const std::string& domain) {
    if (domain.size() > 2 && domain[0] == '*' && domain[1] == '.') {
        return domain.substr(2);
    }
    return domain;
}

} // namespace keen_pbr3
